server:
  port: 8081

spring:
  # 解決 Security 隨機密碼問題
  security:
    user:
      name: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-3c893072-a901211-ba4b.a.aivencloud.com:10093/defaultdb?ssl-mode=REQUIRED&characterEncoding=utf8&serverTimezone=UTC
    username: avnadmin
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

# 💡 移出 spring 層級，這樣才能正確讀取
twilio:
  account_sid: ACcd29c3b55f80662469f2c75ccdf30bd2
  auth_token: 309a4eda08ab821805b81ff41e13911f
  from_number: "+15077765726"

app:
  reset_password_url: "http://localhost:5173/Resetpassword"